apiVersion: v1
kind: Secret
metadata:
  name: 'secret-{{ template "configuration-api.fullname" . }}'
  labels:
    {{- include "configuration-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  appsettings.secrets.json: |
    {
      "ConnectionStrings": {
        "InventoryDatabase": "host={{ .Values.postgres.host }};port=5432;database={{ .Values.postgres.database }};username={{ .Values.postgres.user }};password={{ .Values.postgres.password }}"
      }
    }
