heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - https://es01:9200
    - https://kibana:5601
  ssl:
    certificate_authorities: ["/usr/share/elastic-agent/config/certs/ca/ca.crt"]

- type: icmp
  schedule: '@every 5s'
  hosts:
    - es01
    - kibana

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:es01:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  ssl:
    certificate_authorities: "/usr/share/elastic-agent/config/certs/ca/ca.crt"