trigger:  none

variables:
  - group: Azure_Credential
  - group: inventorydb-deployment

  - name: aksResourceGroup
    value: rg-aks-bootstrap-networking-spoke

  - name: aksName
    value: aksbootstrap

  - name: serviceName
    value: devices-api

  - name: databaseName
    value: devicesDB

  - name: databaseUserName
    value: devicesdb_rw


resources:
  pipelines:
  - pipeline: devices-api-ci # Name of the pipeline resource.
    source: devices-api-ci # The name of the pipeline referenced by this pipeline resource.
    project: iac # Required only if the source pipeline is in another project
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

stages:
  - template: ./templates/service-deploy-cd.yaml
    parameters:
      aksResourceGroup:     $(aksResourceGroup)
      aksName:              $(aksName)
      serviceName:          $(serviceName)
      databaseName:         $(databaseName)
      databaseUserName:     $(databaseUserName)
      databaseUserPassword: $(configurationdb-rw)
