version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge
  elastic:
    external:
      name: monitoring_elastic

services:

  seq:
    image: datalust/seq:latest
    networks:
      - dockerapi-dev

  caching:
    image: redis:alpine
    networks:
      - dockerapi-dev

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "32781:5432"
    restart: always
#    volumes:
#      - db_volume:/var/lib/postgresql/data
#      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "bloguser"
      POSTGRES_PASSWORD: "bloguser"
      POSTGRES_DB: "serversDB"
    networks:
      - dockerapi-dev

volumes:
  db_volume: