version: '3.4'

networks:
  dockerapi:
    external:
      name: backends_dockerapi-dev

  #elastic:
  #  external:
  #    name: monitoring_elastic

services:
  inventory.configuration.api:
    image: ${DOCKER_REGISTRY-}inventoryconfigurationapi
    build:
      context: .
      dockerfile: configuration/Inventory.Configuration.Api/Dockerfile
    networks:
      - dockerapi
      #- elastic

  inventory.devices.api:
    image: ${DOCKER_REGISTRY-}inventorydevicesapi
    build:
      context: .
      dockerfile: devices/Inventory.Devices.Api/Dockerfile
    depends_on:
      - "inventory.configuration.api"
    networks:
      - dockerapi
      #- elastic


  inventory.gateway.api:
    image: ${DOCKER_REGISTRY-}inventorygatewayapi
    build:
      context: .
      dockerfile: gateway/Inventory.Gateway.Api/Dockerfile
    depends_on:
      - "inventory.configuration.api"
      - "inventory.devices.api"
    networks:
      - dockerapi
      #- elastic


  inventory.networks.api:
    image: ${DOCKER_REGISTRY-}inventorynetworksapi
    build:
      context: .
      dockerfile: networks/Inventory.Networks.Api/Dockerfile
    depends_on:
      - "inventory.configuration.api"
    networks:
      - dockerapi
      #- elastic

