---
name: "Calcul build version"
description: "Identify build scope and calcul the build version"

inputs:
  service:
    description: "Service to build"
    required: true

runs:
  using: "composite"
  steps:

    - name: Set branch name as env variable
      run: |
        currentbranch=$(echo ${GITHUB_REF##*/})
        echo "running on $currentbranch"
        echo "BRANCH=$currentbranch" >> $GITHUB_ENV
      shell: bash

    - name: Get Last Branch and Semantic Version Containing String to ${{ inputs.service }}
      id: lrb
      uses: jessicalostinspace/github-action-get-regex-branch@v1.0.2
      with:
        regex-string: 'release'
