---
name: "Calcul build version"
description: "Identify build scope and calcul the build version"

inputs:
  service:
    description: "Service to build"
    required: true

runs:
  using: "composite"
  steps:

    - name: Set branch name as env variable
      run: |
        currentbranch=$(echo ${GITHUB_REF##*/})
        echo "running on $currentbranch"
        echo "BRANCH=$currentbranch" >> $GITHUB_ENV
      shell: bash

    - name: Bumping Major Index
      id: bump_version_major
      # if: contains(github.event.pull_request.title, 'major')
      uses: christian-draeger/increment-semantic-version@1.1.0
      with:
        current-version: 0.2.0
        version-fragment: 'major'

