---
parameters:
  - name: serviceName
    type: string

  - name: projectPath
    type: string

  - name: testsProjectPath
    type: string

  - name: infrastructureProjectPath
    type: string

  - name: 'preTest'
    type: stepList
    default: []

  - name: dockerFile
    type: string

  - name: repositoryName
    type: string

  - name: chartPath
    type: string
    default: 'builds/kubernetes/charts'

  - name: chartName
    type: string

  - name: debugPipelineFlow
    type: boolean
    default: false

stages:

  # ---------------------------------------------------------------------------
  # Build and tests service
  # ---------------------------------------------------------------------------
  - stage: BuildApplication
    displayName: Build Service
    jobs:
      - job: DotnetBuild
        displayName: Build Service

        steps:
          - template: ./steps/dotnet-ci-steps.yaml
            parameters:
              serviceName:       ${{ parameters.serviceName }}
              projectPath:       ${{ parameters.projectPath }}
              debugPipelineFlow: ${{ parameters.debugPipelineFlow }}

      - job: DotnetUnitTests
        displayName: Tests Service
        dependsOn:
          - DotnetBuild

        steps:
          - template: ./steps/dotnet-unittests-ci-steps.yaml
            parameters:
              serviceName:       ${{ parameters.serviceName }}
              projectPath:       ${{ parameters.projectPath }}
              testsProjectPath:  ${{ parameters.testsProjectPath }}
              preTest:           ${{ parameters.preTest }}
              debugPipelineFlow: ${{ parameters.debugPipelineFlow }}

  # ---------------------------------------------------------------------------
  # Build Container image and chart
  # ---------------------------------------------------------------------------

  - stage: BuildImages
    displayName: Build image and chart
    dependsOn:
      - BuildApplication

    jobs:
      - job: DockerBuild
        displayName: Build and publish docker images
        variables:
          tag: $(Build.BuildId)

        steps:
          - template: ./steps/container-ci-steps.yaml
            parameters:
              serviceName:       ${{ parameters.serviceName }}
              repositoryName:    ${{ parameters.repositoryName }}
              dockerFile:        ${{ parameters.dockerFile }}
              dockerTags:        $(tag)
              debugPipelineFlow: ${{ parameters.debugPipelineFlow }}

      - job: HelmBuild
        displayName: Build and publish Helm chart
        dependsOn:
          - DockerBuild

        variables:
          tag: $(Build.BuildId)

        steps:
          - template: ./steps/chart-ci-steps.yaml
            parameters:
              serviceName:       ${{ parameters.serviceName }}
              chartPath:         ${{ parameters.chartPath }}
              chartName:         ${{ parameters.chartName }}
              chartVersion:      $(tag)
              debugPipelineFlow: ${{ parameters.debugPipelineFlow }}

  # ---------------------------------------------------------------------------
  # Build Databases scripts
  # ---------------------------------------------------------------------------
  - stage: BuildDbScripts
    displayName: Build database scripts
    dependsOn:
      - BuildApplication

    jobs:
      - job: DatabaseBuild
        displayName: Build database scripts
        variables:
          tag: $(Build.BuildId)

        steps:
          - template: ./steps/databases-ci-steps.yaml
            parameters:
              serviceName:               ${{ parameters.serviceName }}
              projectPath:               ${{ parameters.projectPath }}
              infrastructureProjectPath: ${{ parameters.infrastructureProjectPath }}
              debugPipelineFlow:         ${{ parameters.debugPipelineFlow }}

