---
parameters:
  - name: aksResourceGroup
    type: string

  - name: aksName
    type: string

  - name: serviceName
    type: string

  - name: chartName
    type: string

  - name: artifactVersionNumber
    type: string

  - name: containerRegistry
    type: string
    default: 'aksbootstrap'

  - name: containerRegistryFqdn
    type: string
    default: 'aksbootstrap.azurecr.io'

  - name: hasDatabase
    type: boolean
    default: true

  - name: databaseName
    type: string
    default: ''

  - name: databaseUserName
    type: string
    default: ''

  - name: databaseUserPassword
    type: string
    default: ''

  - name: resourcePipelineId
    type: string
    default: ''

stages:

  - stage: deployTests
    # dependsOn:
    #   - BuildImages

    jobs:
      - deployment: deployTests
        # pool:
        #   vmImage: 'ubuntu-16.04'
        environment: Dynamic-Inventory-Tests
        strategy:
          runOnce:
            preDeploy:
              steps:

                - task: PublishBuildNumber@0
                  name: PublishBuildNumber
                  displayName: Publish build numbers
                  inputs:
                    semanticVersioning: '${{ parameters.artifactVersionNumber }}'
                    uniqueCounter: ''

                - ${{ if parameters.hasDatabase }}:
                  - template: ./steps/databases-cd-steps.yaml
                    parameters:
                      aksResourceGroup:     ${{ parameters.aksResourceGroup }}
                      aksName:              ${{ parameters.aksName }}
                      serviceName:          ${{ parameters.serviceName }}
                      databaseName:         ${{ parameters.databaseName }}
                      databaseUserName:     ${{ parameters.databaseUserName }}
                      databaseUserPassword: ${{ parameters.databaseUserPassword }}
                      resourcePipelineId:   ${{ parameters.resourcePipelineId }}

            deploy:
              steps:

                - template: ./steps/chart-cd-steps.yaml
                  parameters:
                    aksResourceGroup:      ${{ parameters.aksResourceGroup }}
                    aksName:               ${{ parameters.aksName }}
                    serviceName:           ${{ parameters.serviceName }}
                    chartName:             ${{ parameters.chartName }}
                    containerRegistry:     ${{ parameters.containerRegistry }}
                    containerRegistryFqdn: ${{ parameters.containerRegistryFqdn }}
                    artifactVersionNumber: ${{ parameters.artifactVersionNumber }}
                    databaseName:          ${{ parameters.databaseName }}
                    databaseUserName:      ${{ parameters.databaseUserName }}
                    databaseUserPassword:  ${{ parameters.databaseUserPassword }}
