version: '3.4'

services:
  inventory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__InventoryDbConnectionString=host=postgres_image;port=5432;database=blogdb;username=bloguser;password=bloguser
    ports:
      - "32773:80"
      - "32772:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro