apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  config.json: |
    {
      "ConnectionStrings": {
        "InventoryDatabase": "host=postgresql.postgresql;port=5432;database=ConfigurationDB;username=configurationdb_rw;password=$(configurationdb-rw)"
      }
    }
