variables:
  - group: Azure_Credential

stages:
- stage: BuildApplication
  displayName: Build Inventory Service
  jobs:
    - job: DotnetBuild
      displayName: Build Service
      steps:

        - task: DotNetCoreCLI@2
          displayName: Build Inventory.API.sln
          inputs:
            command: 'build'
            projects: 'Services/Inventory.API.sln'

    - job: DotnetTest
      displayName: Test Service
      dependsOn: DotnetBuild
      steps:

        - task: AzureKeyVault@1
          displayName: 'Load client secret from Azure Key vault'
          inputs:
            azureSubscription: 'Visual Studio Enterprise (62177529-73f0-4e11-a584-5d3526dc6999)'
            keyVaultName:  'mesfVault'
            secretsFilter: 'Ansible-Automation'

        - task: PowerShell@2
          displayName: 'Update AppSettings file before testing'
          inputs:
            targetType: 'inline'
            script: |
              $pathToJson = "Services/Inventory.UnitTests/appsettings.json"
              $a = Get-Content $pathToJson | ConvertFrom-Json
              $a.Azure.ClientSecret = $(Ansible-Automation)
              $a.Azure.TenantId = $(TenantId)
              $a.Azure.ClientId = $(ClientId)
              $a | ConvertTo-Json | set-content $pathToJson

        - task: DotNetCoreCLI@2
          displayName: Test Inventory.API.sln
          inputs:
            command: 'test'
            projects: 'Services/Inventory.API.sln'

    - job: DockerBuild
      dependsOn: DotnetBuild
      steps:

          - bash: echo "Hello"

- stage: DeployApplication
  dependsOn:
    - BuildApplication

  jobs:
    - deployment: B1
      pool:
        vmImage: 'ubuntu-16.04'
      environment: env1
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo $(myOutputVar)