stages:
- stage: BuildApplication
  displayName: Build Inventory Service
  jobs:
    - job: DotnetBuild
      displayName: Build Service
      steps:

        - task: DotNetCoreCLI@2
          displayName: Build Inventory.API.sln
          inputs:
            command: 'build'
            projects: 'Services/Inventory.API.sln'

    - job: DotnetBuild
      displayName: Test Service
      dependsOn: DotnetBuild
      steps:

        - displayName: 'Update AppSettings file before testing'
          powershell: |
            $pathToJson = "Services/Inventory.UnitTests/appsettings.json"
            $a = Get-Content $pathToJson | ConvertFrom-Json
            $a.Azure.ClientSecret = ${{ parameters.clientSecret }}
            $a.Azure.TeantId = ${{ parameters.TeantId }}
            $a.Azure.ClientId = ${{ parameters.ClientId }}
            $a | ConvertTo-Json | set-content $pathToJson

        - task: DotNetCoreCLI@2
          displayName: Test Inventory.API.sln
          inputs:
            command: 'test'
            projects: 'Services/Inventory.API.sln'

    - job: DockerBuild
      dependsOn: DotnetBuild
      steps:

          - bash: echo "Hello"

- stage: DeployApplication
  dependsOn:
    - BuildApplication

  jobs:
    - deployment: B1
      pool:
        vmImage: 'ubuntu-16.04'
      environment: env1
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo $(myOutputVar)