variables:
  - group: Azure_Credential

stages:
- stage: BuildApplication
  displayName: Build Inventory Service
  jobs:
    - job: DotnetBuild
      displayName: Build Service
      steps:

        - task: DotNetCoreCLI@2
          displayName: Build Inventory.API.sln
          inputs:
            command: 'build'
            projects: 'Services/Inventory.API.sln'

    - job: DotnetTest
      displayName: Test Service
      dependsOn: DotnetBuild
      steps:

        - task: PowerShell@2
          displayName: 'Update AppSettings file before testing'
          inputs:
            targetType: 'inline'
            script: |
              $pathToJson = "Services/Inventory.UnitTests/appsettings.json"
              $a = Get-Content $pathToJson | ConvertFrom-Json
              $a.Azure.ClientSecret = $env:VAR_CLIENT_SECRET
              $a.Azure.TenantId = $env:VAR_TENANT_ID
              $a.Azure.ClientId = $env:VAR_CLIENT_ID
              $a | ConvertTo-Json | set-content $pathToJson
          env:
            VAR_CLIENT_SECRET: $(ClientSecret)
            VAR_TENANT_ID: $(TenantId)
            VAR_CLIENT_ID: $(ClientId)

        - task: DotNetCoreCLI@2
          displayName: Test Inventory.API.sln
          inputs:
            command: 'test'
            projects: 'Services/Inventory.API.sln'

    - job: DockerBuild
      dependsOn:
        - DotnetBuild
        - DotnetTest
      steps:

          - bash: echo "Hello"

- stage: DeployApplication
  dependsOn:
    - BuildApplication

  jobs:
    - deployment: B1
      pool:
        vmImage: 'ubuntu-16.04'
      environment: env1
      strategy:
        runOnce:
          deploy:
            steps:
            - bash: echo $(myOutputVar)